# Generated by Django 6.0.5 on 2026-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionset",
            name="resume_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
